# Rust TCP Client

[package]
name = "rust-tcp-server"
version = "1.0.0"
edition = "2018"

[dependencies]
sha-1 = "0.8.2"
base64 = "0.12.1"
colored = "1.9"
banner = "0.0.4"
log4rs = "1.0.0"
log = { version = "0.4.0", features = ["std"] }